# Generated by Django 4.1.4 on 2023-01-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msg_t',
        ),
    ]
