# Generated by Django 4.1.4 on 2023-02-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_usercategoryattempts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategoryattempts',
            options={'verbose_name_plural': 'User Attempts Category '},
        ),
    ]
