# Generated by Django 4.1.4 on 2023-03-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_usercategoryattempts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
